package skeletonkey;

public enum Multitudes {
    COGNITIVE,
    SPIRITUAL,
    ETHICAL,
    AESTHETIC,
    AFFECTIVE,
    VALUES,
    NEEDS,
    VERBAL_LINGUISTIC,
    BODILY_KINESTHETIC,
    VISUAL_SPATIAL,
    LOGICAL_MATHEMATICAL,
    MUSICAL_RHYTHMIC_HARMONIC,
    TEACHING_PEDAGOGICAL,
    NATURALISTIC,
    INTERPERSONAL,
    INTRAPERSONAL,
    EXISTENTIAL
}
