package resources.datatypes.bibliographicdata;

public enum ExerciseSubcategories {
    YOGA,
    GYMNASTICS,
    WRESTLING,
    MARTIAL_ARTS,
    WEIGHT_TRAINING,
    WALKING,
    RUNNING,
    CYCLING,
    BOXING,
    HIKING,
    SWIMMING,
    DANCING,
    CALISTHENICS,
    ROCK_CLIMBING,
    TAI_CHI,
    BASKETBALL,
    FOOTBALL,
    VOLLEYBALL,
    SOCCER,
    BASEBALL,
    SKATEBOARDING,
    SURFING,
    HOCKEY,
    DIVING,
    HIIT,
    CROSS_FIT,
    HEAVY_LIFTING,
    MACHINE_TRAINING,
    SKIING,
    SNOWBOARDING,
    RESISTANCE_TRAINING,
    POWER_TRAINING,
    SPEED_TRAINING,
    ENDURANCE_TRAINING
}
